// Preguntas de juegos con historia. Cada título aporta al menos seis por nivel.
// Se agregan después de las diez preguntas demo de cada nivel.
const GAME_SETS = {
  "game-rearise": [
    [
      ["¿Qué Digimon acompaña al protagonista de ReArise?","Herissmon."],
      ["¿Cómo se llaman los enemigos que imitan a Digimon?","Spirals."],
      ["¿Qué Digimon acompaña a Takumi Hiiragi?","DORUmon."],
      ["¿Qué Digimon acompaña a Michi Shinjo?","Salamon."],
      ["¿Qué Digimon acompaña a Mayu Kohinata?","Kudamon."],
      ["¿Qué Digimon acompaña a Keito Tamada?","Elecmon."],
    ],
    [
      ["¿Qué Digimon aparece desde el móvil antes de evolucionar a Herissmon?","Pusurimon."],
      ["¿Qué afición deportiva tiene Takumi Hiiragi?","Baloncesto."],
      ["¿Qué actividad disfruta especialmente Mayu Kohinata?","Hornear dulces."],
      ["¿En qué clase de agrupación musical toca Keito?","En una big band de jazz."],
      ["¿Qué Digimon acompaña a Nozomi Tamada?","Pumpkinmon."],
      ["¿Qué Digimon acompaña a Sara Shinkai?","Tapirmon."],
    ],
    [
      ["¿En qué Digimon evoluciona Herissmon antes de Stefilmon?","Filmon."],
      ["¿Qué forma perfecta sigue a Filmon?","Stefilmon."],
      ["¿Qué forma final alcanza el compañero del protagonista?","Rasenmon."],
      ["¿Qué Digimon acompaña a Kazuma Natsuyagi?","Bearmon."],
      ["¿Qué Digimon acompaña a la misteriosa Mon?","Huckmon."],
      ["¿Qué cafetería frecuentan los personajes de ReArise?","Café Truffe."],
    ],
    [
      ["¿Qué Digimon acompaña a la dueña Chihiro Tsukimori?","Lopmon."],
      ["¿En qué Digimon evoluciona el Pumpkinmon de Nozomi?","NoblePumpkinmon."],
      ["¿Qué forma descontrolada puede alcanzar Rasenmon?","Rasenmon Fury Mode."],
      ["¿Qué antagonista tiene ojos rojos y voluntad propia entre los Spirals?","Spiral Origin."],
      ["¿Qué investigador se alía con los Spirals en la segunda temporada?","Eiji Futami."],
      ["¿Qué elemento del Mundo Digital intenta tomar Spiral Origin?","El Kernel."],
    ],
    [
      ["¿Qué Caballero Real apoya a Rasenmon frente a Spiral Origin?","JESmon."],
      ["¿Qué grupo angelical recupera el Kernel tras la derrota de Spiral Origin?","Los Tres Grandes Ángeles."],
      ["¿Qué Digimon confiere voluntad individual a Spiral Origin?","GranDracmon."],
      ["¿Qué tipo de Spiral toma Spiral Origin en su primera aparición?","Uno con aspecto de Keramon."],
      ["¿Qué busca crear Spiral Origin destruyendo el Mundo Digital?","Un mundo de Spirals."],
      ["¿Qué propone Eiji para los Spirals al terminar la historia?","Que renazcan como Digimon."],
    ],
  ],
  "game-ryo-wonderswan": [
    [
      ["¿Quién protagoniza los juegos de WonderSwan ligados a Adventure y Tamers?","Ryo Akiyama."],
      ["¿Qué Digimon llama a Ryo al Mundo Digital al iniciar Anode/Cathode?","Agumon."],
      ["¿Qué villano secuestra a los niños elegidos en Anode/Cathode?","Millenniummon."],
      ["¿Qué amigo acompaña a Ryo en Tag Tamers?","Ken Ichijoji."],
      ["¿Qué Digimon conoce Ken como compañero en Tag Tamers?","Wormmon."],
      ["¿Qué Digimon conoce Ryo como compañero en Brave Tamer?","Monodramon."],
    ],
    [
      ["¿Qué dos Digimon se fusionan para formar Millenniummon?","Kimeramon y Machinedramon."],
      ["¿Qué Digimon llega del ordenador de Ken para llamar a los dos amigos?","V-mon."],
      ["¿En qué película ven Ryo y Ken la pelea contra Diablomon?","Our War Game!."],
      ["¿Qué enemigo aparente resulta ser una trampa para Ryo en Tag Tamers?","Un clon de Diablomon."],
      ["¿Qué objeto oscuro infecta a Ken al salvar a Ryo?","Una Semilla de Oscuridad."],
      ["¿Qué juego de Ryo gira en torno a un torneo?","D-1 Tamers."],
    ],
    [
      ["¿A qué niño elegido salva Ryo al final de Anode/Cathode?","Taichi Yagami."],
      ["¿Cómo se llama el sitio duplicado que crea Millenniummon en Tag Tamers?","Un mundo espejo."],
      ["¿Qué criatura reaparece detrás de la trampa de Tag Tamers?","Millenniummon."],
      ["¿Qué premio prometen al ganador del torneo de D-1 Tamers?","Una Bestia Sagrada como compañera."],
      ["¿Qué Digimon encuentra Ryo al caer al pasado en Brave Tamer?","Monodramon."],
      ["¿Qué forma de Millenniummon amenaza la etapa final de Brave Tamer?","ZeedMillenniummon."],
    ],
    [
      ["¿Qué anciano encomienda a Ryo y Ken derrotar a Millenniummon?","Gennai."],
      ["¿Qué domador es el último rival de Ryo en el torneo D-1?","Taichi Yagami."],
      ["¿Qué computadora guía a Ryo a través del tiempo en Brave Tamer?","ENIAC."],
      ["¿Qué computadora se presenta como creadora de los Mundos Digitales?","Atanasoff."],
      ["¿Qué niño estadounidense compite contra Ryo en D-1 Tamers?","Wallace."],
      ["¿Qué Digimon nace del huevo formado tras la unión de Monodramon y Millenniummon?","Cyberdramon."],
    ],
    [
      ["¿Qué identidad revela Millenniummon respecto a Ryo en Brave Tamer?","Su compañero original."],
      ["¿Qué objeto aumenta puntos de Jogress sin fusionar en D-1 Tamers?","JogPlus."],
      ["¿A qué mundo elige viajar Ryo al final de Brave Tamer?","Al mundo de Tamers."],
      ["¿A quién inmoviliza Millenniummon junto a Agumon en Tag Tamers?","Taichi."],
      ["¿Qué forma de Millenniummon aparece bajo la Torre D-1?","MoonMillenniummon."],
      ["¿Quién ayuda a Ryo a analizar líneas de evolución en D-1 Tamers?","Ken Ichijoji."],
    ],
  ],
  "game-super-xros-wars": [
    [
      ["¿Quién dirige Xros Heart en Super Xros Wars?","Taiki Kudo."],
      ["¿Qué Digimon conoce Taiki en la nueva zona del juego?","Spadamon."],
      ["¿Qué versión del juego presenta a Kiriha?","Blue."],
      ["¿Qué versión presenta a Nene?","Red."],
      ["¿Qué sonido traslada a Xros Heart a otra zona?","Una melodía misteriosa."],
      ["¿Cómo se llama la zona central de la historia exclusiva?","LS-tou Zone."],
    ],
    [
      ["¿Qué clase de Digimon es Spadamon?","Un Digimon arma."],
      ["¿Qué Digimon se equipa a Spadamon para convertirse en X4S?","Shoutmon X4."],
      ["¿En qué fusión participa Spadamon junto a Sparrowmon?","Shoutmon X5S."],
      ["¿Quién manipula a Nene en la versión Red?","SkullKnightmon."],
      ["¿Qué fila permite activar DigiXros durante las batallas?","Vanguardia."],
      ["¿Qué fila evita recibir daño enemigo directo?","Retaguardia."],
    ],
    [
      ["¿Qué orden de combate cambia la posición delantera y trasera?","Formación."],
      ["¿Qué arma viviente rival estuvo al servicio de Dynasmon?","Armamon."],
      ["¿Qué Caballero Real encerró a Armamon?","Dynasmon."],
      ["¿Qué señor demonio busca despertar a Armamon?","Barbamon."],
      ["¿Qué programa puede reunir los Digicores de toda la zona?","System Omega."],
      ["¿Qué grupo dirige Barbamon para obtener líderes?","ROG."],
    ],
    [
      ["¿En qué espacio fue sellado Armamon?","Lost Space."],
      ["¿En qué área está ubicado System Omega?","Omega Area."],
      ["¿En qué arma convierte Armamon a Barbamon tras rechazarlo?","Galactic Sword."],
      ["¿Qué antiguo amo intenta recrear Armamon?","Dynasmon."],
      ["¿Qué le ocurrió a la conciencia de Spadamon por obra de Dynasmon?","Fue sellada."],
      ["¿Qué parte de los Digimon quiere reunir Armamon en System Omega?","Sus Digicores."],
    ],
    [
      ["¿Qué forma final surge de Armamon, Barbamon y System Omega?","OmegaArmamon Burst Mode."],
      ["¿Qué organización derrota a OmegaArmamon Burst Mode?","Xros Heart."],
      ["¿Qué grupo de tres vuelve en el combate Platinum Tamer?","Los Bandits."],
      ["¿En qué enemigo se fusionan Uno, Dos y Tres en ese combate?","Ex-Eraser Omega."],
      ["¿Qué técnica de Shoutmon X4S usa a Spadamon como espada luminosa?","Victory Brave."],
      ["¿Qué Digimon adicional distingue a X5S de X4S?","Sparrowmon."],
    ],
  ],
  "game-dawn-dusk": [
    [
      ["¿Qué equipo protagoniza Digimon World Dawn?","Light Fang."],
      ["¿Qué equipo protagoniza Digimon World Dusk?","Night Claw."],
      ["¿Qué Digimon inicial simboliza Dawn?","Coronamon."],
      ["¿Qué Digimon inicial simboliza Dusk?","Lunamon."],
      ["¿En qué ciudad vive Light Fang?","Sunshine City."],
      ["¿En qué ciudad vive Night Claw?","Darkmoon City."],
    ],
    [
      ["¿Quién dirige Light Fang en Dawn?","Glare."],
      ["¿Quién dirige Night Claw en Dusk?","Julia."],
      ["¿Qué nombre japonés tiene Digimon World Dawn?","Sunburst."],
      ["¿Qué nombre japonés tiene Digimon World Dusk?","Moonlight."],
      ["¿Qué dos equipos celebran un combate de rivalidad al principio?","Light Fang y Night Claw."],
      ["¿Qué estructura entre ambas ciudades destruye el ataque inicial?","El puente."],
    ],
    [
      ["¿Qué Digimon es la manifestación física del virus que golpea ambas ciudades?","Grimmon."],
      ["¿A qué regresan muchos Digimon durante el ataque de Grimmon?","A DigiHuevos."],
      ["¿Qué lugar atraviesa Grimmon cuando se le enfrenta por primera vez?","Limit Valley."],
      ["¿Qué dispositivo del mundo es dañado por el ataque inicial?","Los puntos de acceso."],
      ["¿Qué equipo es acusado al principio del desastre en Dawn?","Night Claw."],
      ["¿Qué Digimon acompaña a Koh en Dawn?","Coronamon."],
    ],
    [
      ["¿Qué entidad viral dirige realmente a Grimmon?","Chrono Core."],
      ["¿Qué proyecto antiguo produjo los Chrono Data?","Proyecto YMIR."],
      ["¿Qué forma destructiva de Chronomon originó el Chrono Core?","Chronomon Destroy Mode."],
      ["¿Qué técnica de Grimmon devuelve Digimon a DigiHuevos?","Chrono Destruction."],
      ["¿En qué lugar el virus posee a miembros del equipo rival?","Access Glacier."],
      ["¿En qué zona aparece la forma final ExoGrimmon?","Chaos Brain."],
    ],
    [
      ["¿En qué forma evoluciona Grimmon al unirse con Chrono Core?","ChaosGrimmon."],
      ["¿Qué forma sigue a ChaosGrimmon en el clímax?","ExoGrimmon."],
      ["¿Qué Digimon de Night Claw es poseído por Chrono Core en Dawn?","ChaosGallantmon."],
      ["¿Qué Digimon de Light Fang es poseído en Dusk?","Ophanimon."],
      ["¿Qué ser produce la Digi-Entelechy que fortalece a Chrono Core?","Calumon."],
      ["¿Contra qué ordenador central dirige Chrono Core su plan final?","Yggdrasill."],
    ],
  ],
  "game-story-ds": [
    [
      ["¿Con qué título se vendió Digimon Story de DS fuera de Japón?","Digimon World DS."],
      ["¿Qué organización estudia los rumores de Digimon en el primer Digimon Story?","DATS."],
      ["¿Cómo se llama la agrupación de domadores del juego?","Tamer Union."],
      ["¿Qué Digimon trabaja en la granja del protagonista?","Calumon."],
      ["¿Qué Digimon escapa de Tomomi y ayuda al protagonista?","Pagumon."],
      ["¿Qué dispositivo lleva el protagonista de Digimon Story DS?","Digivice iC."],
    ],
    [
      ["¿Qué bosque explora el protagonista al inicio del juego?","Data Forest."],
      ["¿Qué ciudad funciona como centro de los domadores?","Digi-Central."],
      ["¿Qué instalación guarda a los Digimon fuera del equipo?","DigiFarm."],
      ["¿Cuántos Digimon combaten simultáneamente en el equipo?","Tres."],
      ["¿Qué Digimon persigue a Calumon al comienzo?","Goblimon."],
      ["¿Qué domadora fue la anterior compañera de Pagumon?","Tomomi."],
    ],
    [
      ["¿Qué grupo de domadores encabeza Kain?","Bad Tamers."],
      ["¿Qué alias usa Alphamon en la trama?","Unknown-D."],
      ["¿Qué Digimon ángel fue antiguo amigo de Alphamon?","ClavisAngemon."],
      ["¿Qué Digimon secuestra a Ellie por orden de Unknown-D?","Devimon."],
      ["¿Qué Digimon secuestra a Phil por orden de Unknown-D?","Machinedramon."],
      ["¿Qué chip hace retroceder a Machinedramon a SkullGreymon?","Devolve Chip."],
    ],
    [
      ["¿Qué Digimon legendario intenta despertar Alphamon?","Chronomon."],
      ["¿A quién usa Alphamon como domador de Chronomon?","Kain."],
      ["¿Qué energía roba Alphamon de Calumon para su plan?","Su energía evolutiva."],
      ["¿En qué recinto estaba dormido Chronomon?","Healing Plant."],
      ["¿Qué Digimon resulta del AtlurKabuterimon de Kain con el Data Core?","GranKuwagamon."],
      ["¿Qué Digimon aparece tras purificar a Chronomon Destroy Mode?","Chronomon Holy Mode."],
    ],
    [
      ["¿Qué Digimon representa la forma destructiva del jefe final?","Chronomon Destroy Mode."],
      ["¿Qué causó la maldad inicial de Chronomon al despertar?","El corazón oscurecido de Kain."],
      ["¿Qué Digimon se une a Alphamon para intentar frenar a Chronomon?","ClavisAngemon."],
      ["¿Qué vínculo permite al protagonista superar a Chronomon?","El de domador y Digimon."],
      ["¿Qué Digimon invitado de Savers evoluciona a GeoGreymon?","El Agumon de Masaru."],
      ["¿Qué evolución alcanza el Gaomon de Thomas contra KingEtemon?","MachGaogamon."],
    ],
  ],
  "game-lost-evolution": [
    [
      ["¿Qué Digimon viaja al mundo humano buscando nuevos domadores en Lost Evolution?","Agumon."],
      ["¿Qué fiesta se celebra cuando los niños conocen a Agumon?","Un festival de fuegos artificiales."],
      ["¿Qué parte del sistema evolutivo debe restaurarse en Lost Evolution?","El árbol de evolución."],
      ["¿Cómo se llama el protagonista masculino por defecto?","Shuu."],
      ["¿Cómo se llama la protagonista femenina por defecto?","Kizuna."],
      ["¿Qué trío persigue el protagonista tras la desaparición de sus amigos?","Los Bandits."],
    ],
    [
      ["¿Qué objeto dañado se repara para recuperar evoluciones?","Bug Plates."],
      ["¿En qué se convierte una Bug Plate tras repararla?","En una DigiPlate."],
      ["¿Dónde se coloca una DigiPlate restaurada?","En el árbol de evolución."],
      ["¿Cómo se llama el líder autoproclamado de los Bandits?","Uno."],
      ["¿Qué transporte permite acceder al Mundo Digital en Lost Evolution?","El DigiShip."],
      ["¿Qué niño de Lost Evolution es hermano de Yui?","Hiroyuki."],
    ],
    [
      ["¿Qué organización incluye a los Bandits y a los Erasers?","Selector."],
      ["¿Qué proyecto persigue el grupo Selector?","El plan Defrag."],
      ["¿Qué Digimon acompaña a Asuka en Lost Evolution?","GrapLeomon."],
      ["¿Qué Digimon acompaña al niño Takuto?","WarGrowlmon."],
      ["¿Qué Digimon buscaba una Bug Plate cuando fue atacado?","Gabumon."],
      ["¿Qué lugar aloja a los Digimon que no van de aventura?","La DigiFarm."],
    ],
    [
      ["¿Qué herramienta retira Crystal Bugs de una Bug Plate?","Mega Laser."],
      ["¿Qué herramienta rellena los arañazos de una Bug Plate?","Masilla."],
      ["¿Qué herramienta quita suciedad de una Bug Plate?","Limpiador."],
      ["¿Qué Digimon pudo evolucionar a Devimon al restaurar su placa?","PicoDevimon."],
      ["¿Qué ser virtual dirige el plan de eliminar la evolución?","Kernel."],
      ["¿Qué árbol es el origen de los datos y la evolución en la trama?","El Árbol Antiguo."],
    ],
    [
      ["¿En qué se transforma Kernel antes de llegar a Tera Devast?","Giga Devast."],
      ["¿Qué forma final surge de Giga Devast?","Tera Devast."],
      ["¿Qué Eraser resulta de la combinación de Uno, Dos y Tres?","Ex-Eraser Omega."],
      ["¿Qué Digimon alcanza PicoDevimon después de Devimon en la historia?","VenomMyotismon."],
      ["¿De qué es una copia virtual Kernel?","Del creador humano del Mundo Digital."],
      ["¿Qué actividad de la DigiFarm permite encontrar objetos?","Las expediciones."],
    ],
  ],
  "game-world": [
    [
      ["¿Qué Digimon anciano pide ayuda en el primer Digimon World?","Jijimon."],
      ["¿Quién es el villano humano del primer Digimon World?","Analogman."],
      ["¿Qué ciudad protege Akira en Digimon World 2?","Digital City."],
      ["¿Qué mundo virtual visita Junior en Digimon World 3?","Digimon Online."],
      ["¿Quién protagoniza Digimon World Re:Digitize?","Taiga."],
      ["¿Qué ciudad se reconstruye en Next Order?","Floatia."],
    ],
    [
      ["¿Qué Digimon usa Analogman para el duelo final del primer World?","Machinedramon."],
      ["¿Cómo se llaman los vehículos de los domadores en World 2?","DigiBeetles."],
      ["¿Qué organización terrorista aparece en World 3?","A.o.A."],
      ["¿Qué empresa gestiona Digimon Online en World 3?","MAGAMI."],
      ["¿Qué juego dentro de la historia reúne a Taiga y sus amigos en Re:Digitize?","Digital Monster."],
      ["¿Cuántos compañeros cría a la vez el protagonista de Next Order?","Dos."],
    ],
    [
      ["¿Qué grupo de World 2 se rebeló contra Digital City?","Blood Knights."],
      ["¿Quién lidera a los Blood Knights en World 2?","Crimson."],
      ["¿Qué servidor de World 3 es escenario del comienzo de la aventura?","Asuka."],
      ["¿Qué servidor rival de World 3 sirve de base a A.o.A?","Amaterasu."],
      ["¿Qué empresa construyó DigiTower en Re:Digitize?","GIGO."],
      ["¿En qué Digimon se transforman muchos de los infectados de Next Order?","Machinedramon."],
    ],
    [
      ["¿En qué montaña se enfrenta el jugador a Analogman en el primer World?","Infinity Mountain."],
      ["¿Qué entidad obsesiona a Crimson en World 2?","GAIA."],
      ["¿Qué Digimon artificial planea crear A.o.A en World 3?","BEMmon."],
      ["¿Qué palabra clave lleva a Taiga al evento de Re:Digitize?","Re:Digitize."],
      ["¿Qué ser artificial amenaza a Taiga en Re:Digitize?","Vitium."],
      ["¿Qué Digimon guía la reconstrucción de Floatia en Next Order?","Jijimon."],
    ],
    [
      ["¿Qué forma adopta Crimson al usar ADN de los Digimon Chaos en World 2?","Neo Crimson."],
      ["¿Qué Digimon de World 3 intenta fusionarse con la Tierra?","Snatchmon."],
      ["¿Qué Digimon resulta de la fusión de Snatchmon con un satélite?","Ragnamon."],
      ["¿Quién creó a Vitium en Re:Digitize?","El profesor Petrov."],
      ["¿Qué programa extiende Yggdrasill en la trama de Decode?","El programa X."],
      ["¿Qué dos Caballeros Reales investigan Infinity Mountain en Decode?","Omegamon X y Dukemon X."],
    ],
  ],
  "game-adventure-psp": [
    [
      ["¿Qué serie adapta el RPG Digimon Adventure de PSP?","Digimon Adventure de 1999."],
      ["¿Qué isla aparece como escenario inicial de la adaptación de PSP?","Isla File."],
      ["¿Qué personaje lidera el arco de cruce entre series del juego de PSP?","Taichi Yagami."],
      ["¿Qué película adapta el segundo gran arco del juego de PSP?","Our War Game!."],
      ["¿Cómo se llaman las misiones opcionales nuevas del juego?","Subepisodios."],
      ["¿Qué Digimon inicial del juego ya está en etapa Adulta?","Tailmon."],
    ],
    [
      ["¿Qué Digimon aparece con Daisuke en el arco exclusivo de PSP?","V-mon."],
      ["¿Qué Digimon acompaña a Takato en el cruce de PSP?","Guilmon."],
      ["¿Qué Digimon acompaña a Taiki en ese cruce?","Shoutmon."],
      ["¿Qué Digimon acompaña a Masaru en el cruce?","Agumon."],
      ["¿Qué niño de Frontier se une al cruce del juego?","Takuya Kanbara."],
      ["¿Qué Digimon acompaña a Tagiru en el cruce?","Arresterdramon."],
    ],
    [
      ["¿Qué objetos se insertan en cuadrículas para mejorar a los Digimon?","DigiPieces."],
      ["¿Qué característica social facilita los combos entre compañeros?","La afinidad."],
      ["¿Qué Digimon acompaña a Huckmon durante el arco exclusivo?","Gankoomon."],
      ["¿Qué jefe encabeza la Digital Dungeon alfa?","Shellmon y Seadramon."],
      ["¿Qué pareja de jefes espera en la Digital Dungeon beta?","Leomon y Ogremon."],
      ["¿Qué enemigo aparece dos veces como jefe en la Digital Dungeon gamma?","SkullGreymon."],
    ],
    [
      ["¿Qué Digimon entrena Taichi al comenzar el arco exclusivo de cruce?","Huckmon."],
      ["¿Qué Digimon amenaza a los protagonistas en la adaptación de Our War Game! del juego de PSP?","Diablomon."],
      ["¿Qué Digimon adopta V-mon como invitado en el cruce?","Magnamon."],
      ["¿Qué Digimon adopta Guilmon como invitado en el cruce?","Dukemon."],
      ["¿Qué Digimon adopta Shoutmon como invitado en el cruce?","OmegaShoutmon."],
      ["¿Qué Digimon adopta Agumon de Masaru en el cruce?","ShineGreymon."],
    ],
    [
      ["¿Cuántos puntos de afinidad requiere un niño, salvo Taichi y Yamato, para desbloquear su forma final?","35."],
      ["¿Qué dos niños obtienen su etapa final por la historia sin exigir afinidad?","Taichi y Yamato."],
      ["¿Qué Digimon cierra la secuencia de jefes de la Digital Dungeon eta?","Diablomon."],
      ["¿Qué Digimon de Frontier puede alcanzar KaiserGreymon en el cruce?","Agnimon."],
      ["¿Qué tipo de aliado del cruce no puede controlarse directamente?","Un invitado."],
      ["¿Qué ocurre con los recuerdos del cruce al volver cada héroe a su mundo?","Se borran."],
    ],
  ],
  "game-survive": [
    [
      ["¿Qué tipo de viaje lleva al grupo al mundo de Survive?","Un campamento escolar."],
      ["¿Qué Digimon encuentra Takuma primero en forma de Koromon?","Agumon."],
      ["¿Qué Digimon acompaña a Kaito Shinonome?","Dracmon."],
      ["¿Qué Digimon acompaña a Miu Shinonome?","Shakomon."],
      ["¿Qué Digimon acompaña a Saki Kimishima?","Floramon."],
      ["¿Qué Digimon acompaña a Ryo Tominaga?","Kunemon."],
    ],
    [
      ["¿Qué relación familiar tienen Kaito y Miu?","Son hermanos."],
      ["¿Qué Digimon acompaña a Shuuji Kayama?","Lopmon."],
      ["¿Cómo llaman a los monstruos en el mundo de Survive?","Kemonogami."],
      ["¿Qué lugar investigan Takuma y sus amigos antes de desaparecer?","Un santuario."],
      ["¿Qué Digimon acompaña a la representante de clase Aoi?","Labramon."],
      ["¿Qué Digimon acompaña a Minoru Hinata?","Falcomon."],
    ],
    [
      ["¿Qué tres afinidades de karma guían las decisiones de Takuma?","Moral, Armonía e Ira."],
      ["¿Qué evolución adulta de Agumon corresponde al karma Moral?","Greymon."],
      ["¿Qué evolución adulta de Agumon corresponde al karma de Ira?","Tuskmon."],
      ["¿Qué evolución adulta de Agumon corresponde al karma de Armonía?","Tyranomon."],
      ["¿Qué hermana de Haru lleva décadas atrapada en el otro mundo?","Miyuki Minase."],
      ["¿Qué Digimon acompaña a Miyuki Minase?","Renamon."],
    ],
    [
      ["¿Qué evolución perfecta obtiene Agumon con karma Moral?","MetalGreymon."],
      ["¿Qué evolución perfecta obtiene Agumon con karma de Ira?","Megadramon."],
      ["¿Qué evolución perfecta obtiene Agumon con karma de Armonía?","Triceramon."],
      ["¿Qué ruta especial de Survive requiere una segunda partida?","La ruta Verdadera."],
      ["¿A quién hay que salvar temprano para abrir la ruta Verdadera?","A Ryo Tominaga."],
      ["¿Qué Digimon acompaña a Akiharu Minase?","Garurumon."],
    ],
    [
      ["¿En qué Digimon puede convertirse Labramon al cerrar la ruta de Ira?","Plutomon."],
      ["¿En qué Digimon puede convertirse Dracmon al cerrar la ruta de Armonía?","Voltobautamon."],
      ["¿Qué Digimon puede obtener Agumon al completar la ruta Verdadera?","Huanglongmon."],
      ["¿Qué Digimon acompaña al antagonista Haruchika Minase?","Huanglongmon."],
      ["¿Qué bestia sagrada corresponde al niño Seiryu?","Qinglongmon."],
      ["¿Qué bestia sagrada corresponde al niño Genbu?","Xuanwumon."],
    ],
  ],
  "game-hackers-memory": [
    [
      ["¿Qué papel ocupa Hacker's Memory respecto a Cyber Sleuth?","Una historia paralela."],
      ["¿Qué grupo hacker acoge a Keisuke?","Hudie."],
      ["¿Qué cuenta le roban a Keisuke al comienzo?","Su cuenta de EDEN."],
      ["¿Qué Digimon acompaña a Erika Mishima?","Wormmon."],
      ["¿Quién es el hermano mayor de Erika?","Ryuji Mishima."],
      ["¿Qué personaje de Hudie tiene a Ankylomon como compañero?","Chitose Imai."],
    ],
    [
      ["¿De qué delitos acusan falsamente a Keisuke?","Robo de cuentas."],
      ["¿Qué Digimon es el compañero principal de Ryuji?","Cyberdramon."],
      ["¿En qué lugar se reúne el equipo Hudie?","En un cibercafé."],
      ["¿Qué amigo de la infancia intenta ayudar Keisuke?","Yu Nogi."],
      ["¿Qué miembro de Hudie resuelve encargos en EDEN para limpiar su nombre?","Keisuke Amazawa."],
      ["¿Qué inicial usa el misterioso hacker que hostiga a Keisuke?","K."],
    ],
    [
      ["¿Qué Digimon puede elegir Keisuke como inicial además de Tentomon y Betamon?","Gotsumon."],
      ["¿En qué zona de EDEN estaba encerrado Arcadiamon?","Under Zero."],
      ["¿Qué Digimon protege a Ryuji cuando Arcadiamon despierta?","Cyberdramon."],
      ["¿Qué forma adquiere Arcadiamon al absorber a Cyberdramon?","Arcadiamon Child."],
      ["¿Qué grupo hacker rival encabeza el avatar YUUGO?","ZAXON."],
      ["¿Qué Digimon inicial alternativo a Betamon y Gotsumon puede elegir Keisuke?","Tentomon."],
    ],
    [
      ["¿Qué Digimon absorbe a Chitose en la trama de Hacker's Memory?","Un Eater."],
      ["¿Qué Digimon usa Ryuji tras perder aparentemente a Cyberdramon?","Arcadiamon."],
      ["¿Qué Digimon absorbe Arcadiamon para pasar a su forma Adult?","IceDevimon."],
      ["¿En qué ciudad aparece Arcadiamon Super Ultimate desde un lago?","Odaiba."],
      ["¿Qué criatura surge cuando los Eater Bits se unen a Erika?","Eater Legion."],
      ["¿Con qué Digimon se fusiona Erika al final de la historia?","Wormmon."],
    ],
    [
      ["¿Qué Digimon nace de la unión de Erika y Wormmon?","Hudiemon."],
      ["¿Qué Digimon resulta de la fusión del Ankylomon de Chitose con Angemon?","Shakkoumon."],
      ["¿Qué recurso de Erika permite herir al gigantesco Arcadiamon?","Sus Eater Bits."],
      ["¿Qué Digimon enmascarado manipula a Yu Nogi?","Matadrmon."],
      ["¿En qué Digimon acaba evolucionando el Matadrmon de la máscara?","GranDracmon."],
      ["¿Qué suceso borra a Erika de la nueva línea temporal humana?","La restauración del mundo tras los Eaters."],
    ],
  ],
  "game-cyber-sleuth": [
    [
      ["¿Qué apellido tienen los dos protagonistas seleccionables de Cyber Sleuth?","Aiba."],
      ["¿Cómo se llama el ciberespacio donde comienza la investigación?","EDEN."],
      ["¿Quién dirige la agencia de detectives que acoge a Aiba?","Kyoko Kuremi."],
      ["¿En qué centro comercial está la agencia Kuremi?","Nakano Broadway."],
      ["¿Qué amiga de Aiba viaja con Agumon y Gabumon?","Nokia Shiramine."],
      ["¿Qué amigo de Aiba fue líder del grupo Jude?","Arata Sanada."],
    ],
    [
      ["¿Qué empresa administra EDEN en Cyber Sleuth?","Kamishiro Enterprises."],
      ["¿Qué policía colabora con la agencia Kuremi?","Goro Matayoshi."],
      ["¿Cómo se llama la zona clandestina de EDEN frecuentada por hackers?","Kowloon."],
      ["¿Qué habilidad permite a Aiba desplazarse por redes y aparatos?","Connect Jump."],
      ["¿Qué grupo de hackers utiliza el avatar YUUGO como líder?","ZAXON."],
      ["¿Quién atiende el DigiLab en Cyber Sleuth?","Mirei Mikagura."],
    ],
    [
      ["¿Qué hermana de Yuugo usa su identidad en EDEN?","Yuuko Kamishiro."],
      ["¿Qué Digimon acompaña a Arata Sanada?","Keramon."],
      ["¿En qué Digimon se fusionan los compañeros de Nokia?","Omegamon."],
      ["¿Qué Digimon acompaña a Yuuko Kamishiro?","RizeGreymon."],
      ["¿Qué hacker es el rostro del grupo Demons?","Jimmy KEN."],
      ["¿Qué Digimon acompaña a la inspectora Makiko Date?","Lopmon."],
    ],
    [
      ["¿Qué Digimon ocupa el cuerpo de Kyoko en la trama original?","Alphamon."],
      ["¿Qué Caballero Real ocupa el cuerpo de Rie Kishibe?","LordKnightmon."],
      ["¿Qué científico impulsa los experimentos con Eaters?","Akemi Suedou."],
      ["¿En qué se transforma Arata al fusionarse con un Eater?","Eater Adam."],
      ["¿Qué Digimon usa el avatar YUUGO para combatir?","Machinedramon."],
      ["¿Qué hacker de ZAXON conoce la identidad real de YUUGO?","Fei."],
    ],
    [
      ["¿Qué ordenador central invade Mother Eater en Cyber Sleuth?","Yggdrasill."],
      ["¿Qué función recupera Yggdrasill tras liberarse de los Eaters?","Reparar el Mundo Digital."],
      ["¿Quién fundó la compañía Kamishiro antes de Rie Kishibe?","Satoru Kamishiro."],
      ["¿Quién era el padre de la verdadera Kyoko Kuremi?","Kodai Kuremi."],
      ["¿Qué Digimon acompaña a Arata en su forma posterior a Infermon?","Diablomon."],
      ["¿Qué dos Digimon de Nokia preceden directamente a Omegamon?","WarGreymon y MetalGarurumon."],
    ],
  ],
  "game-time-stranger": [
    [
      ["¿Qué dos protagonistas se pueden elegir en Time Stranger?", "Dan Yuki o Kanan Yuki."],
      ["¿Cómo se llama la amiga de Aegiomon en Time Stranger?", "Inori Misono."],
      ["¿Qué ciudad japonesa queda clausurada al inicio de Time Stranger?", "Shinjuku."],
      ["¿En qué ciudad de Iliad se encuentra su centro urbano?", "Central Town."],
      ["¿Qué Digimon gobierna Central Town?", "Mercurymon."],
      ["¿Qué barrio de Tokio se explora además de Shinjuku?", "Akihabara."],
    ],
    [
      ["¿Cuántos años retrocede el protagonista tras la explosión de Time Stranger?", "Ocho años."],
      ["¿Qué Digimon es el compañero de Inori Misono?", "Aegiomon."],
      ["¿Qué papel tiene el protagonista no elegido?", "Operador de apoyo."],
      ["¿Qué Digimon solicita investigar la Central Tower?", "Mercurymon."],
      ["¿Quién es el padre detective de Inori?", "Kosuke Misono."],
      ["¿Qué zona de Iliad rodea al Árbol del Mundo?", "Gear Forest."],
    ],
    [
      ["¿Qué Digimon es el hermano menor de Minervamon en Time Stranger?", "Coronamon."],
      ["¿Qué Digimon es la hermana menor de Minervamon?", "Lunamon."],
      ["¿Quién administra las puertas entre el mundo humano e Iliad?", "Junomon."],
      ["¿Qué Digimon lidera el poblado de Gear Forest?", "Bacchusmon."],
      ["¿Qué Digimon lleva los asuntos del bosque mientras Bacchusmon bebe?", "Sirenmon."],
      ["¿Qué Digimon se convierte en Aegiochusmon?", "Aegiomon."],
    ],
    [
      ["¿Qué grupo rival abre por la fuerza un Digital Gate en Time Stranger?", "Los Titanes."],
      ["¿Qué Digimon encabeza a los Titanes?", "Plutomon."],
      ["¿Qué guerrero de los Titanes se enfrenta al grupo en un Digital Gate?", "Titamon."],
      ["¿Qué Digimon cura al Hangyomon herido y acaba bajo sospecha?", "Shellmon."],
      ["¿Qué científica de seguridad pública estudia a Aegiomon?", "Monica Simmons."],
      ["¿Quién dirige la unidad policial de casos extraños?", "Kodai Kuremi."],
    ],
    [
      ["¿Qué Digimon gobierna Factorial Area en Time Stranger?", "Vulcanusmon."],
      ["¿Qué aparato creado por Vulcanusmon controla este personalmente?", "Brazos Divinos versión Ω."],
      ["¿Quién dirige el Teatro Entre Tiempos?", "Mirei Mikagura."],
      ["¿Qué canal de vídeo administra Hiroko Sagisaka?", "Occult Tokyo TV."],
      ["¿Qué Digimon llega al mundo humano con una misión y se une al grupo?", "Minervamon."],
      ["¿A qué Digimon de los Titanes prestó ayuda Shellmon?", "Hangyomon."],
    ],
  ],
};

export const GAME_QUESTIONS = Object.fromEntries(
  [1, 2, 3, 4, 5].map((level) => [
    level,
    Object.entries(GAME_SETS).flatMap(([tag, levels]) =>
      levels[level - 1].map(([question, answer]) => ({ question, answer, tags: [tag] })),
    ),
  ]),
);
