// Preguntas adicionales de manga, cómics y novelas.
// Los filtros usan OR y estas entradas se agregan después de las diez demo.
export const LITERATURE_QUESTIONS = {
  1: [
    {"question":"¿Quién protagoniza el manga Digimon Adventure V-Tamer 01?","answer":"Taichi Yagami.","tags":["literature-v-tamer"]},
    {"question":"¿En qué mundo transcurre la aventura principal de V-Tamer 01?","answer":"En el Mundo Digital.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Digimon amenaza con dominar el mundo en V-Tamer 01?","answer":"Demon.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Digimon convocó a Taichi al Mundo Digital en V-Tamer 01?","answer":"Lord HolyAngemon.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Gabumon guía a Taichi y Zero durante su aventura?","answer":"Gabo.","tags":["literature-v-tamer"]},
    {"question":"¿Qué objetos especiales busca Taichi durante su viaje?","answer":"Las V-Tamer Tags.","tags":["literature-v-tamer"]},
    {"question":"¿Quién es el protagonista humano de Digimon Next?","answer":"Tsurugi Tatsuno.","tags":["literature-next"]},
    {"question":"¿Qué Digimon acompaña a Tsurugi en Digimon Next?","answer":"Agumon.","tags":["literature-next"]},
    {"question":"¿Qué Digimon acompaña a Yuu Inui?","answer":"Gaomon.","tags":["literature-next"]},
    {"question":"¿Cuál es el nombre de la chica aliada de Tsurugi y Yuu?","answer":"Ami Kitajima.","tags":["literature-next"]},
    {"question":"¿Qué Digimon es el antagonista demoníaco de Next?","answer":"Barbamon.","tags":["literature-next"]},
    {"question":"¿Cómo se llama el Digimon creado con las DigiMemories?","answer":"NEO.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Quién lidera Xros Heart en el manga Xros Wars?","answer":"Taiki Kudo.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon es el compañero principal de Taiki en el manga?","answer":"Shoutmon.","tags":["literature-xros-wars"]},
    {"question":"¿Cómo se llama el equipo de Kiriha en el manga?","answer":"Blue Flare.","tags":["literature-xros-wars","topic-groups"]},
    {"question":"¿Cómo se llama el grupo que comanda Nene en el manga?","answer":"Twilight.","tags":["literature-xros-wars","topic-groups"]},
    {"question":"¿Qué imperio combate Xros Heart en el manga?","answer":"El Imperio Bagra.","tags":["literature-xros-wars","topic-groups"]},
    {"question":"¿Qué dispositivo permite las DigiXros en el manga?","answer":"El Xros Loader.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué Digimon estudioso acompaña a los protagonistas de Dreamers?","answer":"Bokomon.","tags":["literature-dreamers"]},
    {"question":"¿Qué nombre recibe el compañero de Ritsu?","answer":"Pal.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon de orejas aladas figura entre los aliados de Ritsu?","answer":"Patamon.","tags":["literature-dreamers"]},
    {"question":"¿Qué poder queda sellado en Witchelny?","answer":"La magia.","tags":["literature-dreamers","topic-other-worlds"]},
    {"question":"¿A qué mundo es transportado Ritsu?","answer":"Al Mundo Digital.","tags":["literature-dreamers"]},
    {"question":"¿A qué clase de delincuente digital pertenece Eiji al inicio?","answer":"Cracker.","tags":["literature-seekers"]},
    {"question":"¿Cómo se llama el amigo hacker de Eiji que usa Pulsemon?","answer":"Leon Alexander.","tags":["literature-seekers"]},
    {"question":"¿Qué Digimon acompaña a Leon en Seekers?","answer":"Pulsemon.","tags":["literature-seekers"]},
    {"question":"¿Qué barrio de Wall Slum se asocia con el lobo Loogamon en Seekers?","answer":"La Novena Avenida.","tags":["literature-seekers"]},
    {"question":"¿Qué profesor entrega a Eiji su Digimon Linker?","answer":"Ryusenji.","tags":["literature-seekers","topic-digivices","topic-artifacts"]},
    {"question":"¿Quién protagoniza el webcómic Digimon Liberator?","answer":"Shoto Kazama.","tags":["literature-liberator-comic"]},
    {"question":"¿Cuántos años tiene Shoto al entrar en Liberator?","answer":"19 años.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué relación unía a Shoto y Arisa antes del juego?","answer":"Eran amigos de la infancia.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué hábito le impedía a Shoto ganar partidas?","answer":"Rendirse fácilmente.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué clase de Digimon no convertidos en cartas conoce Shoto en Lacuna?","answer":"Digimon salvajes.","tags":["literature-liberator-comic","topic-other-worlds"]},
    {"question":"¿Cuánto duró la beta cerrada de Liberator?","answer":"Un año.","tags":["literature-liberator-comic"]},
    {"question":"¿Quién protagoniza la novela paralela de Digimon Liberator?","answer":"Yuuki.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué afición artística tiene Yuuki?","answer":"Bailar.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué equipo investiga fallos en la novela Liberator?","answer":"El equipo de depuración.","tags":["literature-liberator-novel"]},
    {"question":"¿Cómo se llama el juego de cartas inmersivo de la novela?","answer":"Digimon Liberator.","tags":["literature-liberator-novel"]},
    {"question":"¿Dónde se desarrolla el juego de la novela?","answer":"En Lacuna.","tags":["literature-liberator-novel","topic-other-worlds"]},
    {"question":"¿Qué meta tiene el equipo con los Digimon salvajes?","answer":"Convertirlos en cartas.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué organización policial investiga los delitos Digimon en Seekers?","answer":"Digipolice.","tags":["literature-seekers"]},
    {"question":"¿Qué sustancia permite sobrevivir al programa X en Chronicle?","answer":"El Anticuerpo X.","tags":["literature-chronicle","topic-x-antibody"]},
    {"question":"¿Cómo se llama el ordenador que gobierna el Mundo Digital de Chronicle?","answer":"Yggdrasill.","tags":["literature-chronicle","topic-digital-world"]},
    {"question":"¿Qué programa amenaza con borrar Digimon en Chronicle?","answer":"El programa X.","tags":["literature-chronicle","topic-x-antibody"]},
    {"question":"¿Cómo se llama el nuevo mundo creado para el Proyecto Arca?","answer":"Nuevo Mundo Digital.","tags":["literature-chronicle","topic-digital-world"]},
    {"question":"¿Qué grupo de caballeros interviene en Chronicle X?","answer":"Los Royal Knights.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups"]},
    {"question":"¿Quién protagoniza el manga Re:Digitize Encode?","answer":"Taiga.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon acompaña a Taiga al inicio de Encode?","answer":"Agumon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon acompaña a Nicolai Petrov en Encode?","answer":"Gaomon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon acompaña a Akiho Rindo en Encode?","answer":"Piyomon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué mundo recorren los protagonistas de Encode?","answer":"El Mundo Digital.","tags":["literature-redigitize-encode","topic-digital-world"]},
    {"question":"¿Cómo se llama el juego dentro de la historia que reúne a Taiga y Nicolai?","answer":"Digital Monster.","tags":["literature-redigitize-encode"]},
  ],
  2: [
    {"question":"¿Qué objeto recibe Taichi como nuevo poder en V-Tamer 01?","answer":"El Digivice 01.","tags":["literature-v-tamer","topic-digivices","topic-artifacts"]},
    {"question":"¿Qué nombre tiene el continente recorrido por Taichi y Zero?","answer":"Folder.","tags":["literature-v-tamer"]},
    {"question":"¿Quién es la hermana menor de Neo Saiba?","answer":"Rei Saiba.","tags":["literature-v-tamer"]},
    {"question":"¿Qué aliado de Taichi dirige la resistencia del castillo en V-Tamer 01?","answer":"Leomon (Leo).","tags":["literature-v-tamer"]},
    {"question":"¿En qué lugar buscan Taichi y Zero la última V-Tamer Tag?","answer":"En el Árbol del Cielo.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Digimon es compañero de Ami Kitajima?","answer":"Pitchmon.","tags":["literature-next"]},
    {"question":"¿Quién tiene a Peckmon como compañero en Next?","answer":"Shou Kahara.","tags":["literature-next"]},
    {"question":"¿En qué Digimon evoluciona el Agumon de Tsurugi antes de RiseGreymon?","answer":"GeoGreymon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿En qué Digimon evoluciona el Gaomon de Yuu antes de MachGaogamon?","answer":"Gaogamon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿A qué humano manipula Barbamon con su técnica Death Lure en Digimon Next?","answer":"Shou Kahara.","tags":["literature-next"]},
    {"question":"¿A qué dios del Mundo Digital se enfrenta la trama de Next?","answer":"Yggdrasill.","tags":["literature-next","topic-lore"]},
    {"question":"¿Quién es la hermana menor de Nene en el manga Xros Wars?","answer":"Kotone.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon fusiona Shoutmon para formar X2?","answer":"Ballistamon.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué Digimon se suma a X2 para formar X3?","answer":"Dorulumon.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué humano acompaña a Taiki y Akari desde el mundo real?","answer":"Zenjiro.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon acompaña a Kiriha junto a Greymon?","answer":"MailBirdramon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué general Bagra empuña una enorme espada?","answer":"Tactimon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué tipo de jugador es Ritsu al inicio de Dreamers?","answer":"Un jugador casero.","tags":["literature-dreamers"]},
    {"question":"¿Quién llama a Ritsu al Mundo Digital?","answer":"Pal (Pulsemon).","tags":["literature-dreamers"]},
    {"question":"¿En qué pueblo conoce Ritsu a varios Digimon?","answer":"Asunaro.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon mago recupera la memoria gracias a Ritsu y Pal?","answer":"Wizarmon.","tags":["literature-dreamers"]},
    {"question":"¿Qué forma alcanza Pulsemon durante Dreamers?","answer":"Bulkmon.","tags":["literature-dreamers","topic-evolution"]},
    {"question":"¿Qué alias usa Eiji en Seekers?","answer":"Fang.","tags":["literature-seekers"]},
    {"question":"¿Qué alias usa Leon Alexander?","answer":"Judge.","tags":["literature-seekers"]},
    {"question":"¿Cómo se llama el equipo cracker en el que se infiltra Eiji?","answer":"Sons of Chaos.","tags":["literature-seekers"]},
    {"question":"¿Qué siglas identifican a Sons of Chaos?","answer":"SoC.","tags":["literature-seekers"]},
    {"question":"¿Qué dispositivo de muñeca usa Eiji para vincularse con Loogamon?","answer":"Digimon Linker.","tags":["literature-seekers","topic-digivices","topic-artifacts"]},
    {"question":"¿Qué corporación fabrica el Digimon Linker?","answer":"Abadin Electronics.","tags":["literature-seekers","topic-digivices","topic-artifacts"]},
    {"question":"¿Qué Digimon acompaña a Owen Dreadnought?","answer":"Elizamon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué Digimon acompaña a Violet Inboots?","answer":"Ghostmon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué Digimon acompaña a Yao Qinglan?","answer":"Sangomon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué Digimon acompaña a Cool Boy?","answer":"Omekamon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué Digimon acompaña a Close?","answer":"Sunarizamon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué Digimon acompaña a Winr?","answer":"FunBeemon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon acompaña a Ryutaro Williams?","answer":"Tyrannomon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon acompaña a Suzune Kazuki?","answer":"Frigimon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon acompaña a Altea?","answer":"Espimon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon acompaña a Mirai Kinosaki?","answer":"Hanimon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon acompaña a Unchained?","answer":"Maquinamon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon es compañero de Kouta en Chronicle?","answer":"DORUmon.","tags":["literature-chronicle"]},
    {"question":"¿Qué Digimon es compañero de Yuji en Chronicle?","answer":"Ryudamon.","tags":["literature-chronicle"]},
    {"question":"¿A qué región envía Yggdrasill a los Royal Knights en Chronicle X?","answer":"Al Viejo Mundo Digital.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups","topic-digital-world"]},
    {"question":"¿Qué Digimon vigila y juzga a los muertos en el Área Oscura?","answer":"Anubimon.","tags":["literature-chronicle","topic-digital-world"]},
    {"question":"¿Qué Royal Knight propone reglas para detener las guerras del Viejo Mundo?","answer":"Jesmon.","tags":["literature-chronicle","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué Digimon llega al Área Oscura para contener a los fugitivos?","answer":"Exammon.","tags":["literature-chronicle","topic-digital-world"]},
    {"question":"¿Qué nombre recibe la versión ampliada del juego que inspira Encode?","answer":"Re:Digitize Decode.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon aparece como compañera de Mirei Mikagura en Encode?","answer":"Angewomon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué otro Digimon acompaña a Mirei junto a Angewomon?","answer":"LadyDevimon.","tags":["literature-redigitize-encode"]},
    {"question":"¿En qué Digimon evoluciona Piyomon en Encode?","answer":"Birdramon.","tags":["literature-redigitize-encode","topic-evolution"]},
    {"question":"¿Cómo se llama el Digimon que acompaña a Yuuya Kuga en Encode?","answer":"Black.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué personaje de apellido Petrov acompaña a Taiga?","answer":"Nicolai.","tags":["literature-redigitize-encode"]},
  ],
  3: [
    {"question":"¿Qué Digimon custodia el castillo aliado atacado por el ejército de Demon?","answer":"HolyAngemon.","tags":["literature-v-tamer"]},
    {"question":"¿Qué grupo de tres domadores sirve inicialmente a Neo?","answer":"Alias III.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Digimon acompaña a Hideto en el combate contra Taichi?","answer":"Omegamon.","tags":["literature-v-tamer"]},
    {"question":"¿Qué técnica nace del vínculo de Taichi y Zero contra Omegamon?","answer":"Dragon Impulse.","tags":["literature-v-tamer","topic-abilities"]},
    {"question":"¿Qué objeto lleva Rei que oculta el Digimental legendario?","answer":"Un collar.","tags":["literature-v-tamer","topic-digimentals","topic-artifacts"]},
    {"question":"¿Qué forma Mega alcanza el Agumon de Tsurugi?","answer":"VictoryGreymon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿Qué forma Mega alcanza el Gaomon de Yuu?","answer":"Z'dGarurumon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿En qué Digimon evoluciona Peckmon en la línea de Shou?","answer":"Yatagaramon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿En qué Digimon evoluciona Pitchmon en la línea de Ami?","answer":"MarineAngemon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿Cómo se llaman los componentes que Barbamon reúne para completar a NEO?","answer":"DigiMemories.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Qué pequeño Digimon convoca a Tsurugi al Mundo Digital?","answer":"Piximon.","tags":["literature-next"]},
    {"question":"¿Qué Digimon sustituye a MadLeomon en la versión manga?","answer":"MachLeomon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon disfraza de humanos a los miembros digitales de Xros Heart?","answer":"Wizarmon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon enfrenta Xros Heart en Odaiba en el manga?","answer":"Blastmon.","tags":["literature-xros-wars"]},
    {"question":"¿Quién es el hermano de Bagramon que dirige su propia facción Twilight?","answer":"DarkKnightmon.","tags":["literature-xros-wars","topic-groups"]},
    {"question":"¿Qué Digimon se agrega a X4 para crear Shoutmon X5?","answer":"Sparrowmon.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué Digimon resulta de fusionar Greymon con MailBirdramon en el manga?","answer":"MetalGreymon.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué reino mágico aparece en Dreamers?","answer":"Witchelny.","tags":["literature-dreamers","topic-other-worlds"]},
    {"question":"¿Qué Digimon provocó la crisis de Witchelny?","answer":"Phelesmon.","tags":["literature-dreamers","topic-other-worlds"]},
    {"question":"¿Qué Digimon espía guía a Ritsu y Pal hacia el Mar de la Memoria?","answer":"Espimon.","tags":["literature-dreamers"]},
    {"question":"¿Qué Deva custodia un santuario en Dreamers?","answer":"Sandiramon.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon se burla de Pal antes de enfrentarse a él en Dreamers?","answer":"Ogremon.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon de Ghost Game aparece brevemente con Hiro?","answer":"Gammamon.","tags":["literature-dreamers"]},
    {"question":"¿Quién dirige el equipo policial Digipolice?","answer":"Yulin Xue.","tags":["literature-seekers"]},
    {"question":"¿Quién es la subdirectora de Digipolice?","answer":"Satsuki Tamahime.","tags":["literature-seekers"]},
    {"question":"¿Qué alias adopta el líder de Sons of Chaos?","answer":"Tartarus.","tags":["literature-seekers"]},
    {"question":"¿Qué red social utilizan muchos crackers en Seekers?","answer":"GriMM.","tags":["literature-seekers"]},
    {"question":"¿Qué técnica une la mente humana al Digicore de un Digimon?","answer":"Mind Link.","tags":["literature-seekers","topic-abilities"]},
    {"question":"¿Qué Digimon acompaña a Zenith en el webcómic?","answer":"Vemmon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué puesto académico cursa Shoto al comenzar Liberator?","answer":"Primer año de universidad.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué cargo ocupa Yao Qinglan en I.D.E.A.?","answer":"Directora técnica.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué puesto ocupó Owen antes de entrar en Liberator?","answer":"Campeón mundial de cartas Digimon.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué rasgo de los NPC provoca conflictos en Liberator?","answer":"Se rebelan contra los jugadores.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué alias usa el niño Saikiyo en la novela inglesa?","answer":"Winr.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué función cumplen Yuuki y sus compañeros en Liberator?","answer":"Depuradores.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué anomalía descubren en la beta de Liberator?","answer":"Digimon salvajes sin carta.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué lugar secreto sirve de base al equipo de depuración?","answer":"El Jardín.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué inteligencia artificial administra el juego junto a Espimon?","answer":"Altea.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué tipo de mazo utiliza Winr?","answer":"Royal Base Control.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué dos Royal Knights investigan primero el Viejo Mundo Digital?","answer":"Craniummon y Sleipmon.","tags":["literature-chronicle","topic-royal-knights","topic-groups","topic-digital-world"]},
    {"question":"¿Qué Digimon intenta imponer una «Death-X-Evolution» a todos?","answer":"GranDracmon.","tags":["literature-chronicle","topic-x-antibody"]},
    {"question":"¿En qué zona es sellado GranDracmon en Chronicle X?","answer":"En el Área Oscura.","tags":["literature-chronicle","topic-x-antibody","topic-digital-world"]},
    {"question":"¿Qué Señora Demonio X lidera la fuga masiva del Área Oscura?","answer":"Lilithmon X.","tags":["literature-chronicle","topic-x-antibody","topic-demon-lords","topic-groups","topic-digital-world"]},
    {"question":"¿Qué facción habita la capa inferior Cocytus?","answer":"Los Siete Grandes Señores Demonio.","tags":["literature-chronicle","topic-demon-lords","topic-groups","topic-digital-world"]},
    {"question":"¿Quién derrota a Ogudomon X con Knights' Intruder?","answer":"Jesmon GX.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups","topic-demon-lords"]},
    {"question":"¿Qué antagonista de Encode tiene formas Baby, Adult y Ultimate?","answer":"Vitium.","tags":["literature-redigitize-encode"]},
    {"question":"¿Cómo se llama el monumento que conserva recuerdos del Mundo Digital en Encode?","answer":"Memorial Stella.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué montaña explora un equipo de Digimon con Anticuerpo X en Encode?","answer":"Infinity Mountain.","tags":["literature-redigitize-encode","topic-x-antibody","topic-digital-world"]},
    {"question":"¿Qué personaje aparece en Encode con dos compañeras, Angewomon y LadyDevimon?","answer":"Mirei Mikagura.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué evolución de Gaomon aparece en la etapa final de Encode?","answer":"Gaogamon.","tags":["literature-redigitize-encode","topic-evolution"]},
    {"question":"¿Qué compañía aparece vinculada a la trama digital de Encode?","answer":"GIGO.","tags":["literature-redigitize-encode"]},
  ],
  4: [
    {"question":"¿En qué Digimon evoluciona Zeromaru al alcanzar el nivel Mega?","answer":"UlforceVeedramon.","tags":["literature-v-tamer","topic-evolution"]},
    {"question":"¿Qué objetivo persigue Neo tras desobedecer a Demon?","answer":"Crear un mundo nuevo.","tags":["literature-v-tamer"]},
    {"question":"¿Qué poder permite a Zero aumentar sus capacidades en la batalla final?","answer":"Overwrite.","tags":["literature-v-tamer","topic-evolution"]},
    {"question":"¿Qué le ocurre a Zeromaru tras recibir la técnica de Arkadimon?","answer":"Queda al borde de la muerte.","tags":["literature-v-tamer"]},
    {"question":"¿Qué ayuda permite recuperarse a Zeromaru tras el ataque de Arkadimon?","answer":"La energía de sus aliados.","tags":["literature-v-tamer"]},
    {"question":"¿Qué personaje es la conciencia de Yggdrasill en Next?","answer":"Norn Mikihara.","tags":["literature-next","topic-lore"]},
    {"question":"¿Qué Digimon es uno de los tres comandantes de Barbamon y tiene armadura roja?","answer":"Chaosdramon.","tags":["literature-next"]},
    {"question":"¿Qué comandante de Barbamon tiene aspecto de samurái?","answer":"Zanbamon.","tags":["literature-next"]},
    {"question":"¿Qué comandante de Barbamon surge de HolyAngemon?","answer":"Murmukusmon.","tags":["literature-next"]},
    {"question":"¿Qué DigiMemory estaba en manos de Tsurugi?","answer":"La del Dragón.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Qué DigiMemory estaba en manos de Yuu?","answer":"La de la Bestia.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Qué grupo sustituye a la orden DigiMemory como apoyo en el manga?","answer":"Los Royal Knights.","tags":["literature-xros-wars","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué entidad acompaña a los Royal Knights en ese papel?","answer":"Homeostasis.","tags":["literature-xros-wars","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué Digimon pretende despertar Bagramon en el manga?","answer":"ZeedMillenniummon.","tags":["literature-xros-wars"]},
    {"question":"¿En qué Digimon luminoso culmina la historia de Shademon vinculado a Nene?","answer":"Luminamon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué general Bagra pertenece a los Siete Grandes Señores Demonio?","answer":"Lilithmon.","tags":["literature-xros-wars","topic-demon-lords","topic-groups"]},
    {"question":"¿Qué destino tiene DarkKnightmon en el final del manga?","answer":"Sobrevive y se redime.","tags":["literature-xros-wars"]},
    {"question":"¿Qué roba Phelesmon para sellar la magia de Witchelny?","answer":"El conocimiento del reino.","tags":["literature-dreamers","topic-other-worlds"]},
    {"question":"¿Qué Digimon de la familia de los demonios acompaña a Phelesmon?","answer":"Boogiemon.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon se enfrenta a Pal tras infiltrarse en el castillo?","answer":"Devimon.","tags":["literature-dreamers"]},
    {"question":"¿En qué mar se refugia Wizarmon mientras intenta recuperar sus recuerdos?","answer":"El Mar de la Memoria.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon alienígena figura entre los encuentros de Dreamers?","answer":"Vademon.","tags":["literature-dreamers"]},
    {"question":"¿Qué quería robar Espimon en Dreamers?","answer":"Datos sobre la evolución de Pulsemon.","tags":["literature-dreamers"]},
    {"question":"¿Quién es el verdadero Tartarus?","answer":"Kosuke Kisakata.","tags":["literature-seekers"]},
    {"question":"¿Qué alias usa Marvin Jackson dentro de Sons of Chaos?","answer":"Song Smith.","tags":["literature-seekers"]},
    {"question":"¿Qué significan las siglas DMIA en Seekers?","answer":"Digital Missing In Action.","tags":["literature-seekers"]},
    {"question":"¿Qué Digimon resulta de la evolución de Loogamon a nivel Campeón?","answer":"Loogarmon.","tags":["literature-seekers","topic-evolution"]},
    {"question":"¿Qué nueva forma definitiva alcanza el compañero de Shoto?","answer":"Vortexdramon.","tags":["literature-liberator-comic","topic-evolution"]},
    {"question":"¿Qué tipo de mazo utiliza Shoto?","answer":"Agresión de aves.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué tipo de mazo utiliza Violet basado en un trío legendario?","answer":"Tres Mosqueteros.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué ciudad de Lacuna es su distrito central?","answer":"Jewel.","tags":["literature-liberator-comic","topic-other-worlds"]},
    {"question":"¿Quién creó al conserje autónomo Altea?","answer":"Yao Qinglan.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué desarrolladora creó el pod de metaverso que usa Liberator?","answer":"T.A.L.E.","tags":["literature-liberator-novel"]},
    {"question":"¿Quién convenció a un Frigimon salvaje para que fuera su compañero?","answer":"Suzune Kazuki.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon salvaje domó Chitose Horaiji durante la beta?","answer":"Kimeramon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué función acepta Suzune en el equipo de Liberator?","answer":"Investigadora de fallos.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Royal Knight X interviene en el duelo entre Barbamon X y DarkKnightmon X?","answer":"LordKnightmon X.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups","topic-demon-lords"]},
    {"question":"¿Qué Royal Knight X enfrenta a Demon X en Chronicle X?","answer":"UlforceVeedramon X.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué Royal Knight X salva a Gankoomon herido?","answer":"Gallantmon X.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué Digimon X combate junto a Justimon X contra Mephismon X?","answer":"Seasarmon X.","tags":["literature-chronicle","topic-x-antibody"]},
    {"question":"¿Qué Digimon acompaña a Alphamon como espada en su forma Ouryuken?","answer":"Ouryumon.","tags":["literature-chronicle","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué domadora de Encode se oculta tras el alias «Nyanko Tamer»?","answer":"Akiho Rindo.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué parentesco une al profesor Petrov con Nicolai en Encode?","answer":"Es su padre.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon intenta contener a Vitium para que Taiga escape en Encode?","answer":"Monzaemon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué programa fue creado para destruir a los Vitium en Encode?","answer":"Gospel Structure.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué poder permite a Taiga extraer datos basura de los Memorial Stella en Encode?","answer":"Decode.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué especie es Black, el compañero de Yuuya en Encode?","answer":"BlackWarGreymon X.","tags":["literature-redigitize-encode"]},
  ],
  5: [
    {"question":"¿Qué forma alcanza Zero mediante el Digimental?","answer":"UlforceVeedramon Future Mode.","tags":["literature-v-tamer","topic-digimentals","topic-artifacts","topic-evolution"]},
    {"question":"¿Qué emblema comparten los dos Taichi para impulsar la evolución de sus Digimon en «Un nuevo coraje»?","answer":"El del Valor.","tags":["literature-v-tamer"]},
    {"question":"¿Qué técnica de Arkadimon deja a Zeromaru al borde de la muerte en V-Tamer 01?","answer":"Dot Matrix.","tags":["literature-v-tamer"]},
    {"question":"¿Qué domador invoca Demon para enfrentarlo a Taichi en V-Tamer 01?","answer":"Neo Saiba.","tags":["literature-v-tamer"]},
    {"question":"¿Qué enemigo ve frustrado su plan de dominar el Mundo Digital cuando Neo lo traiciona?","answer":"Demon.","tags":["literature-v-tamer"]},
    {"question":"¿Qué Digimon enemigo hace retroceder al Greymon de Tsurugi hasta Agumon?","answer":"Peckmon.","tags":["literature-next","topic-evolution"]},
    {"question":"¿Qué Digimon sabotea la DigiMemory mecánica para impedir que NEO obedezca?","answer":"Andromon.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Qué Digimon sirve de estratega a Barbamon en Next?","answer":"Datamon.","tags":["literature-next"]},
    {"question":"¿Qué DigiMemory poseía Piximon antes de que se la robaran?","answer":"La Sagrada.","tags":["literature-next","topic-artifacts"]},
    {"question":"¿Qué dispositivo recibe Tsurugi antes de la evolución a VictoryGreymon?","answer":"Digimon Twin R.","tags":["literature-next","topic-digivices","topic-artifacts"]},
    {"question":"¿Qué Digimon derrota a Barbamon fusionado con Yggdrasill en Next?","answer":"VictoryGreymon.","tags":["literature-next"]},
    {"question":"¿Qué Digimon constituye el adversario final del manga Xros Wars?","answer":"UltimateChaosmon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué forma de Shoutmon aparece en la batalla final del manga?","answer":"Shoutmon X7 Superior Mode.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué DigiXros añade a Mushroomon a Ballistamon?","answer":"Ballistamon MC.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Qué DigiXros combina a Sparrowmon con Ballistamon?","answer":"Sparrowmon AB.","tags":["literature-xros-wars","topic-special-evolution"]},
    {"question":"¿Cómo se llama la forma potenciada de MachLeomon?","answer":"Mush-Upped MachLeomon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué Digimon fusiona a Kimeramon y Machinedramon para crear a Millenniummon en el manga Xros Wars?","answer":"Shademon.","tags":["literature-xros-wars"]},
    {"question":"¿Qué técnica de Phelesmon somete a otros Digimon en Dreamers?","answer":"Demon Shout.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon libera Pal del control de Phelesmon mediante Thunder Dread?","answer":"Wizarmon.","tags":["literature-dreamers"]},
    {"question":"¿Qué técnica usa Wingdramon para vencer a los Kuwagamon que amenazan el pueblo?","answer":"Blaze Sonic Breath.","tags":["literature-dreamers"]},
    {"question":"¿Qué personaje de Dreamers tiene a Wingdramon como compañero?","answer":"Jo Wakamiya.","tags":["literature-dreamers"]},
    {"question":"¿Qué Digimon con aspecto de criatura abisal aparece entre los rivales de Dreamers?","answer":"Dagomon.","tags":["literature-dreamers"]},
    {"question":"¿A qué Rey Demonio suplica ayuda Phelesmon tras ser vencido por Pal?","answer":"Barbamon.","tags":["literature-dreamers"]},
    {"question":"¿Qué nivel Mega alcanza el Pulsemon de Leon?","answer":"Kazuchimon.","tags":["literature-seekers","topic-evolution"]},
    {"question":"¿Qué Digimon Mega acompaña al profesor Ryusenji?","answer":"Dorugoramon.","tags":["literature-seekers"]},
    {"question":"¿Qué problema de Mind Link deja a una persona como DMIA?","answer":"Superar el tiempo límite.","tags":["literature-seekers","topic-abilities"]},
    {"question":"¿Qué efecto tiene evolucionar demasiado durante un Mind Link?","answer":"Acorta el tiempo disponible.","tags":["literature-seekers","topic-abilities","topic-evolution"]},
    {"question":"¿A qué se dedica Owen Dreadnought fuera del juego?","answer":"Ingeniero.","tags":["literature-liberator-comic"]},
    {"question":"¿Qué personaje del webcómic fue hacker antes de dirigir la tecnología de I.D.E.A.?","answer":"Yao Qinglan.","tags":["literature-liberator-comic"]},
    {"question":"¿Quién dirigió la configuración inicial de Lacuna?","answer":"Cool Boy.","tags":["literature-liberator-comic","topic-other-worlds"]},
    {"question":"¿Qué personaje de la novela usa un mazo de Lucemon?","answer":"Dokuson Aruba.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué personaje usa un mazo NSo Beatdown en la novela?","answer":"Reina Oumi.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué personaje usa un mazo Composite Control?","answer":"Chitose Horaiji.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon se hizo amigo de Reina Oumi?","answer":"DemiDevimon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué estructura colosal del Jardín recuerda a un D-Storage?","answer":"Avalon.","tags":["literature-liberator-novel"]},
    {"question":"¿Qué Digimon X planea crear a Ogudomon X usando siete cuerpos?","answer":"Lucemon X.","tags":["literature-chronicle","topic-x-antibody","topic-demon-lords","topic-groups"]},
    {"question":"¿Qué Digimon X surge de la fusión de siete Diaboromon X?","answer":"Ogudomon X.","tags":["literature-chronicle","topic-x-antibody","topic-demon-lords","topic-groups"]},
    {"question":"¿Qué Royal Knight X cede su poder a Jesmon para que alcance GX?","answer":"Gankoomon X.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups"]},
    {"question":"¿Qué técnica final usa Jesmon GX contra Ogudomon X?","answer":"Knights' Intruder.","tags":["literature-chronicle","topic-x-antibody","topic-royal-knights","topic-groups","topic-demon-lords"]},
    {"question":"¿Qué Digimon X vuelve para combatir junto a Ophanimon X contra sus versiones oscuras?","answer":"Cherubimon X (bueno).","tags":["literature-chronicle","topic-x-antibody"]},
    {"question":"¿Qué Digimon acompaña a Rina Shinomiya en Encode?","answer":"V-mon.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué mujer envía a Taiga el programa Digitize para llevarlo al Mundo Digital?","answer":"Mirei Mikagura.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué Digimon enemigo es una forma de Lucemon presente en Encode?","answer":"Lucemon Satan Mode.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué entidad llamada 7D6 figura entre los adversarios de Encode?","answer":"Yggdrasill.","tags":["literature-redigitize-encode"]},
    {"question":"¿Qué forma X de Omegamon participa en la exploración de Infinity Mountain?","answer":"Omegamon X.","tags":["literature-redigitize-encode","topic-x-antibody","topic-digital-world"]},
    {"question":"¿Qué forma de Vitium enfrentan Greymon y Gaogamon durante la batalla final de Encode?","answer":"Vitium Adult.","tags":["literature-redigitize-encode"]},
  ],
};
